# Generated by Django 6.1 on 2026-08-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
    ]
